#!/usr/bin/env bash
# This script loop from 1 to 10 and when it reaches on the nineth number it print hello world
counter=1

while [ $counter -le 10 ]
do
  if [ $counter -eq 9 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  
  counter=$((counter + 1))
done
